- name: Apply Common
  hosts: all
  tasks:
  - import_role:
      name: common
- name: Install Jenkins
  hosts: host04
  become: true
  tasks:
  - import_role:
      name: java
  - import_role:
      name: jenkins