- name: Apply Common
  hosts: all
  tasks:
  - import_role:
      name: common
- name: Install Jenkins
  hosts: jenkinshosts
  become: true
  tasks:
  - import_role:
      name: java
  - import_role:
      name: jenkins
- name : Install Docker
  hosts: jenkinshosts
  become: true
  tasks:
      - import_role:
            name: docker
      - import_role:
            name: docker-registry