- name: Reboot
  shell: "sleep 5 && shutdown -r now"
  listen: "Reboot required"
  async: 1
  poll: 0
- name: Wait reboot completed
  listen: "Reboot required"
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 20
    timeout: 300