- name: Install JDK
  import_role: 
    name: java

- name: Add Jenkins Repo
  shell: "echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list"
  become: true

- name: Add APT Key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
  become: true

- name: Add Jenkins Repo
  shell: "apt update"
  become: true

- name: Install Jenkins Binaries
  apt:
    name: jenkins
    state: present
  become: true

- name: Enable Jenkins Service
  systemd:
    name: jenkins
    enabled: true
    state: started
  become: true
  