---
- name: Install PIP3
  apt:
    name: python3-pip
    
- name: Install PIP
  apt:
    name: python-pip  

- name: PIP Install Docker-PY
  pip:
    name: docker-py
    state: present

- name: Start local docker registry
  docker_container: 
    name: "docker-registry"
    image: registry:2
    exposed_ports:
      - 5000
    state: present
